export const REQUEST_TOP_RATED_INIT = "REQUEST_TOP_RATED_INIT";
export const FETCH_TOP_RATED_INIT = "FETCH_TOP_RATED_INIT";
export const REQUEST_TOP_RATED_SUCCESS = "REQUEST_TOP_RATED_SUCCESS";
export const REQUEST_TOP_RATED_FAILED = "REQUEST_TOP_RATED_FAILED";
