export const REQUEST_ACTIONS_INIT = "REQUEST_ACTIONS_INIT";
export const FETCH_ACTIONS_INIT = "FETCH_ACTION_INIT";
export const REQUEST_ACTIONS_SUCCESS = "REQUEST_ACTIONS_SUCCESS";
export const REQUEST_ACTIONS_FAILED = "REQUEST_ACTIONS_FAILED";
