export const REQUEST_TRENDINGS_INIT = "REQUEST_TRENDINGS_INIT";
export const FETCH_TRENDINGS_INIT = "FETCH_TRENDINGS_INIT";
export const REQUEST_TRENDINGS_SUCCESS = "REQUEST_TRENDINGS_SUCCESS";
export const REQUEST_TRENDINGS_FAILED = "REQUEST_TRENDINGS_FAILED";
export const ISADDED_TRENDINGS = "ISADDED_TRENDINGS";
export const ISREMOVED_TRENDINGS = "ISREMOVED_TRENDINGS";
